[versions]
kotlin = "2.2.20-Beta2"
kotlinxSerialization = "1.9.0"
clikt = "5.0.3"

[libraries]
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
cliktNative = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }


